### ISSUE TITLE
Climatizationcontrols not working with id.3 2021

### ISSUE THREAD

**Issue by Hanzanka** [tillsteinbach/WeConnect-python#36]
I am tryng to start vw id.3 climate control by calling "vehicle.controls.climatizationControl.value = ControlOperation.START", but it seems like it is not doing anything. The code runs with no exceptions but nothing happens at the car. Starting the climate control via the weconnect-id app works, but I have to presss the "start"-button multiple times before something happens, but it still works with the app.

**Comment by Hanzanka** [comment]
Update: The car wasn't driven in few hours, so i went to the car and drove it for few kms and after that the climatization controls began to work!

**Comment by tillsteinbach** [comment]
I also had the problem this morning. It might be temporary.
There are two error cases. You can get an exception raised right away if starting fails. But there are situations where the command is received at the server, but later fails in the car. You can find that out when you update and then check the climatisationStatus. It will have an entry in the requests list containing a requests object with a status. The status can be out of: 
```
SUCCESSFULL = 'successful'
FAIL = 'fail'
POLLING_TIMEOUT = 'polling_timeout'
IN_PROGRESS = 'in_progress'
QUEUED = 'queued'
DELAYED = 'delayed'
TIMEOUT = 'timeout'
FAIL_VEHICLE_IS_OFFLINE = 'fail_vehicle_is_offline'
FAIL_IGNITION_ON = 'fail_ignition_on'
FAIL_BATTERY_LOW = 'fail_battery_low'
FAIL_PLUG_ERROR = 'fail_plug_error'
FAIL_CHARGE_PLUG_NOT_CONNECTED = 'fail_charge_plug_not_connected'
UNKNOWN = 'unknown status'
```
it will start in QUEUED state, then move to IN_PROGRESS and then result in SUCCESSFULL or any of the failure states. That will help you finding out what happened with your control command.
Instead of manually updating you can also register for evens in the climatisationStatus with a callback and set enableTracker() on your WeConnect instance. This one will poll for itself until the Request is in SUCCESSFULL or FAILED state.

**Comment by Hanzanka** [comment]
If the list containing requests in climatisationStatus contains more than one request, so how do i know which one was the most recent. I did some testing when there was 3 requests listed and they seemed to change indexes.

**Comment by hovant** [comment]
I have had problems on swithing heating on with ID.4 using mobile app. Typically I need to repeat it 3 times before it activates. Today I clicked only once and waited by the car. It went on after waiting for 2 minutes. So you just have to be patient. If the car has been driven recently, it is faster.
